apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol 
  labels:
    storage-type: nfs
spec:
#  storageClassName: generic
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /shared 
    server: 192.168.26.10
  persistentVolumeReclaimPolicy: Retain 